config/routes.rb
Rails.application.routes.draw do
 

  namespace :profile do
  get 'users/show'
  end

  namespace :profile do
  get 'users/edit'
  end

  namespace :profile do
  get 'users/update'
  end

  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  resources :users 
  
  namespace :admin do
    resources :movies, :users
  end
  
  namespace :profile do 
    resources :users
  end

  resource :session, only: [:new, :create, :destroy, :edit, :update]

  root to: 'movies#index'

end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < ApplicationController
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  def index
    @user = current_user
    @movies = Movie.all
    if params[:category] != "any" && params[:search].present?
      @movies = @movies.category_search(params[:search])
      if params[:runtime] != "any" 
        @movies = @movies.runtime(params[:runtime])
      end
    end

    if params[:runtime] != "any" && params[:category] == "any" 
      @movies = @movies.runtime(params[:runtime])
    end

    if params[:search].present? && params[:category] == "any" && params[:runtime] == "any"
      @movies = @movies.category_search(params[:search])
    end

    if params[:kind] != "all"
      @movies = @movies.where(category: params[:kind])
    end
  end

  def show
  	@movie = Movie.find(params[:id])
  end

  def new
  	@movie = Movie.new
  end

  def edit
  	@movie = Movie.find(params[:id])
  end

 def create
    @movie = Movie.new(movie_params)
    @movie.update(category: params[:category])

    if @movie.save 
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end


  def update 
  	@movie = Movie.find(params[:id])  

  	if  @movie.update_attributes(movie_params)
        @movie.update(category: params[:category])
        @movie.save
  		redirect_to movie_path(@movie)
  	else
			render :edit
  	end
  end

  def destroy 
  	@movie = Movie.find(params[:id])
  	@movie.destroy 
  	redirect_to movies_path 
  end


  protected 

  def movie_params
  	params.require(:movie).permit(
  		:title, :release_date, :director, :runtime_in_minutes, :poster_image_url, :description, :movieposter
  		)
  end

end

app/helpers/admin/movies_helper.rb
module Admin::MoviesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end

end

app/views/movies/_form.html.erb
<div class="well">
  <div class="form">
    
    <%= form_for @movie, :html => {:multipart => true} do |f| %>
      <div class="form-group">
        <%= f.label "title" %><br>
        <%= f.text_field "title" %>
      </div>
      <div>
        <%= f.label "release_date" %><br>
        <%= f.date_field "release_date" %>
      </div>
      <div>
        <%= f.label "director" %><br>
        <%= f.text_field "director" %>
      </div>
        <div>
        <%= f.label "category"%>
        <%= select_tag :category, options_for_select(['all', 'comedy', 'action', 'romance', 'drama', 'horror'])%>
      </div>
      <div>
        <%= f.label "runtime_in_minutes" %><br>
        <%= f.number_field "runtime_in_minutes" %>
      </div>
      <div>
        <%= f.label "add the movie poster here" %><br>
        <%= f.file_field :movieposter %>
      </div>
        <%= f.label "or add the Url to the movie poster here" %><br>
        <%= f.text_field "poster_image_url" %>
      <div>
        <%= f.label "description" %><br>
        <%= f.text_area "description" %>
      </div>
      <div>
        <%= f.submit "Submit" %> 
      </div>
    <% end %>

    <%= form_for @movie do |f| %>
      <% if @movie.errors.any? %>
        <div>
          <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
          <ul>
            <% @movie.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/movies/_movie.html.erb
	<div class="container">
		<div class="movie_well well col-sm-12">


			<div class="comment_well well pull-right col-sm-8" >
				<h5><%= link_to "write a review for this #{movie.title.capitalize}", new_movie_review_path(movie) %></h5>
			 		<% movie.reviews.each do |review| %>
			 			<h6> <%=link_to "Posted By #{review.user.firstname.capitalize}", profile_user_path(review.user)  %></h6>
			 			<h6><%= review.text %></h6>
			 			<h6><%= review.user.firstname.capitalize%> gave this <%= review.rating_out_of_ten %> out of 10 </h6><hr>	
			 		<% end %>
			</div>

			<h2><%= link_to movie.title, movie_path(movie) %></h2>
			<h6><%= movie.category %></h6> 
		  <%= image_tag movie.movieposter_url(:thumb).to_s %>
		  <h3><%= movie.release_date %></h3>
		  <h5>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h5>
		  <h6><%= movie.description %></h6>
			
			<div>
				<% if movie.review_average.present? %>
					<h3>Average review out of <%= movie.review_average %> / 10</h3>
				<% end %>
			</div>

		</div>
	</div>

app/views/movies/index.html.erb
<div class="title_search container">
	<h1 class="title">Rotten Mangoes</h1>
<div class="row">
	<section class="col-sm-6">
		<h4 class="color_submit"><%= link_to "Submit a movie!", new_movie_path %></h4>
		<% if current_user %>
			  <h4>Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)</h4>
		  	<% if user_is_admin?(current_user) %>
		   		<h4 class="color_submit"><%= link_to "admin panel", admin_users_path %></h4>
		  	<% end %>
			<% else %>
		  	<%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
			<% end %>


		<%= form_tag movies_path, :method => 'get' do %>
			<h4>Search Movies</h4>
			<p><%= select_tag :category, options_for_select(["any",'Director', 'Title']) %>
				<%= select_tag :runtime, options_for_select([["any", "any"], ["Under 90 min", "0 90"], ["Between 90 and 120 minutes", "91 120", ], ["Over 120 minutes", "121 1000"]])%>
				<%= text_field_tag	:search, params[:search] %>
				<%= submit_tag "Search", :name => nil %>
			</p>
		<% end %>

		<div class="search_bars">
			<%= form_tag profile_users_path, :method => 'get' do %>
				<h4>Search User Profile</h4>
				<%= text_field_tag :profile, params[:search] %> 
				<%= submit_tag "Search", :name => nil %>
			<% end %>
		</div>
		
		<div class="search_profile">
			<%= form_tag movies_path, :method => 'get' do %>
			<h4>Filter By Category</h4>	
			<%= select_tag :kind, options_for_select(['all', 'comedy', 'action', 'romance', 'drama', 'horror']) %>
			<%= submit_tag "Filter", :name => nil %>
			<% end %>
		</div>
	</section>	


<div class="col-sm-3 pull-right profile_pic_wrapper">
	<% if current_user %>
		<% if current_user.photo.present? %>
		
		<div class="profile_pic  well ">
			<%= image_tag @user.photo_url(:thumb).to_s %>
		<h5><%= link_to "edit your profile", edit_profile_user_path(current_user.id) %></h5>

	<% end %>
		</div>
<% end %>
</div>
</div><!--row-->

<div class="movie_panel container col-sm-3">
	<h2><% @movies.each do |movie| %><h2>
		<%= render partial: "movie", locals: {movie: movie} %>
	<% end %>
</div>

app/views/movies/new.html.erb
<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %><br/>


<h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, confirm: "You sure?" %>)</h2>
<%= image_tag @movie.movieposter_url.to_s %>
<h3><%= @movie.release_date %></h3>
<h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
<p><%= @movie.description %></p>
<p><%= formatted_date(@movie.release_date) %></p>



<hr>



<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small>- <%= review.user.full_name %></small><br/>
  <% end %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
<% end %>