config/routes.rb
Rails.application.routes.draw do
 

  namespace :profile do
  get 'users/show'
  end

  namespace :profile do
  get 'users/edit'
  end

  namespace :profile do
  get 'users/update'
  end

  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  resources :users 
  
  namespace :admin do
    resources :movies, :users
  end
  
  namespace :profile do 
    resources :users
  end

  resource :session, only: [:new, :create, :destroy, :edit, :update]

  root to: 'movies#index'

end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	has_many :reviews 

	mount_uploader :photo, ProfilePhotoUploader

	  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

	def index
    if current_user.admin
    	@users = User.all.page(params[:page]).per(10)
    else
      redirect_to movies_path, notice: "Sorry you do not have these privileges!"
    end
	end

  def show
    session[:user_id] = session[:fake]
    session[:fake] = nil
    redirect_to admin_users_path
  end

  def reset

  end

  def edit 
    @user = User.find(params[:id].to_i)
  end

  def update
    @user = User.find(params[:id].to_i)
  end

end

app/controllers/profile/users_controller.rb
class Profile::UsersController < ApplicationController
  
  def index 
  	@user = User.find_by(email: params[:profile])

  	if @user 
  		@user 
  	else 
  		redirect_to movies_path
  	end
  end

  def show
  	@user = User.find( params[:id].to_i )
  end

  def edit
    @user = User.find_by( params[:id] )
  end

  def update
    @user = User.find( params[:id] )
    if @user.id == current_user.id
      @user.update_attributes(user_params)
      if @user.admin == true
        @user.admin = true
      end
      redirect_to movies_path
    else
      redirect_to movies_path, notice: "sorry you are not this user"
    end 

      
  end


  protected 

   def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :photo)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def show
    
  end

  def destroy 
    user = User.find(params[:id].to_i)
    user.delete
    UserMailer.delete_email(user).deliver
    redirect_to admin_users_path
  end


  def update
    @user = User.find(params[:id].to_i)
    @user.update_attributes(
      email: params[:user][:email],
      firstname: params[:user][:firstname],
      lastname: params[:user][:lastname]
      ) 

    if params[:admin] == "1"
        @user.admin = true
    else 
        @user.admin = false 
    end 

    @user.save
    redirect_to admin_users_path
  end


  protected 

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :photo)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper

	def user_is_admin?(current_user) 
		current_user.admin == true
	end

end

app/helpers/profile/users_helper.rb
module Profile::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<h1>Edit User</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname" %>
  </div> 

  <div>
    <%= f.label "Add Your Photo" %><br>
    <%= f.file_field :photo %>
  </div>

  <div>
    <%= f.label "password" %><br>
    <%= f.password_field "password" %>
  </div>

  <div>
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field "password_confirmation" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/edit.html.erb
<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1> Welcome to the admin page </h1>

<h2> All Users </h2>
<hr> 

<% @users.each do |user|%>
<% if user != current_user %>
		<h3> User <%=	user.id %> 
		<h4><%=link_to user.firstname, edit_session_path(user) %> 
		<%= link_to user.lastname.capitalize, edit_session_path(user)	 %></h4>
		<h4><%= user.email %></h4>
		<% if user.admin == true %>
		<h5>This user has admin privileges</h5>
		<% end %>
		<h6><%= link_to "Delete user", user, method: :delete  %> | <%= link_to "Edit User", edit_admin_user_path(user) %></h6>	
		<hr>	
	<% end %>
<% end %>
<%= paginate @users %>

<h2><%= link_to "Back to movies", movies_path %></h2>

app/views/admin/users/show.html.erb
<h1> Welcome to the admin page </h1>

<h2> All Users </h2>
<hr> 

<% @users.each do |user|%>
<% if user != current_user %>
		<h3> User <%=	user.id %> 
		<h4><%= names_to_string(user.firstname, user.lastname) %></h4>
		<h4><%= user.email %></h4>
		<h4><%= user.admin %>
		<h4><%= link_to "Delete user", user, method: :delete  %></h4>	
		<hr>	
	<% end %>
<% end %>
<%= paginate @users %>