config/routes.rb
Rails.application.routes.draw do
 

  namespace :profile do
  get 'users/show'
  end

  namespace :profile do
  get 'users/edit'
  end

  namespace :profile do
  get 'users/update'
  end

  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  resources :users 
  
  namespace :admin do
    resources :movies, :users
  end
  
  namespace :profile do 
    resources :users
  end

  resource :session, only: [:new, :create, :destroy, :edit, :update]

  root to: 'movies#index'

end

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
      <% if user_is_admin?(current_user) %>
      	<%= link_to "admin panel", admin_users_path %>
      <% end %>
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %> | 
      <% end %>
    <% if current_user %>
      <% if session[:fake]  %>
        <%= link_to "Go Back To Admin Panel", admin_user_path(session[:fake])  %>
      <% end %>			
    <% end %>   
  </small>

</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  </div>
</body>
</html>